[font]
size = 10.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[keyboard]
bindings = [
	# Paste from clipboard (uses 'action')
	{ key = "V", mods = "Control|Shift", action = "Paste" },

	# Copy to clipboard (uses 'action')
	{ key = "C", mods = "Control|Shift", action = "Copy" }
]

[window]
opacity = 1.0
padding = { x = 10, y = 10 }

[colors.primary]
background = "0x111827"
foreground = "0xD1D5DB"

[colors.cursor]
text   = "0x111827"
cursor = "0xD1D5DB"

[colors.normal]
black   = "0x111827"
red     = "0xFCA5A5"
green   = "0xB1E3AD"
yellow  = "0xFBC19D"
blue    = "0xBAE6FD"
magenta = "0x957FB8"
cyan    = "0xDDD6FE"
white   = "0xA5F3FC"

[colors.bright]
black   = "0x6B7280"
red     = "0xFCA5A5"
green   = "0xB1E3AD"
yellow  = "0xFBC19D"
blue    = "0xBAE6FD"
magenta = "0x938AA9"
cyan    = "0xDDD6FE"
white   = "0xA5F3FC"
